# Generated by Django 5.0.6 on 2024-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('datetimeAdded', models.DateTimeField()),
                ('quantAdded', models.IntegerField()),
            ],
        ),
    ]
