# Generated by Django 5.0.6 on 2024-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('prodPrice', models.IntegerField()),
                ('prodDesc', models.CharField(max_length=100)),
                ('prodAvailQuant', models.IntegerField()),
                ('prodImage', models.ImageField(upload_to='')),
                ('prodCategory', models.CharField(max_length=100)),
            ],
        ),
    ]
